name: Build Plugins

on: push

jobs:
  build:
    if: ${{ github.repository != 'Artemis-RGB/Artemis.PluginTemplate' && '[ -f .template ]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: dotnet publish src/Artemis.Plugins.Parappa2/Artemis.Plugins.Parappa2.csproj -c Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Parappa2Plugin
          path: src/Artemis.Plugins.Parappa2/bin/x64/Release/net10.0/